### ISSUE TITLE
Add automatic retries for contexts that aren't ready

### ISSUE THREAD

**Issue by fregante** [pixiebrix/webext-messenger#11]
- As mentioned in https://github.com/pixiebrix/pixiebrix-extension/pull/1065/files#diff-c3806057390e818bbc24d6fe22f6b956da8c9acd11af84c6b8625fb57bca2c92R155

**Comment by twschiller** [comment]
It would be great if these retries could also be tied to chatter (i.e., ready messages), to avoid unnecessary pauses due to getting unlucky with the re-try interval

One example use case being context menus:
1. user click context menu
2. background page listener gets menu event
3. background page injects content script
4. background page waits for content script to be initialized
5. background page sends context menu event

**Comment by fregante** [comment]
I think this would cause noise because it'd travel on the same channel that sends the actual message.

From the content script’s perspective:

1. The tab opens
2. CS loads
3. Messenger sends READY… _**to who?**_ Ok, let's send it to background for now
4. Now background isn't ready… so **_should it start its own retry loop_** for this READY message?

After #18, retries happen when the connection fails entirely, which is when `onMessage` has not been called at all in the context. The failure is immediate and, I'd expect, pretty lightweight, so I'd rather just retry frequently instead.

I think that for this intent, the time a READY message would save is minimal.
