### ISSUE TITLE
Support messaging with the offscreen page

### ISSUE THREAD

**Issue by fungairino** [pixiebrix/webext-messenger#273]
- The offscreen page’s `__getTabData` call was throwing an error, causing the correct receiver to fail in responding with the right `tabData`.
- The offscreen page, similar to the background service worker, lacks a tab, which this library did not handle correctly.

Notes:
See change that was reverted due to this bug: https://github.com/pixiebrix/pixiebrix-extension/commit/2021198cba9b4497afeb2db17d741cbf641a8326

Action item from: https://www.notion.so/pixiebrix/Postmortem-Release-2-1-6-13543b21a253809bab4cd2aace909433?pvs=4

**Comment by grahamlangford** [comment]
Related: https://github.com/fregante/webext-detect/pull/32

**Comment by fregante** [comment]
I added support for offscreen document detection to `webext-detect`:

- https://github.com/fregante/webext-detect/pull/32

As mentioned in an email to Todd, the messenger was likely failing because the offscreen document was not being properly detected. Also this line needs `isBackground() || isOffscreenDocument()`
